---@meta

---@class ABP_PalRandomIncidentObjectPlacement_PalNest_Yeti_C : APalRandomIncidentObjectPlacement
---@field BP_PalRandomIncidentPlacementDropItemDataComponent4 UBP_PalRandomIncidentPlacementDropItemDataComponent_C
---@field BP_PalRandomIncidentPlacementDropItemDataComponent3 UBP_PalRandomIncidentPlacementDropItemDataComponent_C
---@field BP_PalRandomIncidentPlacementEggDataComponent2 UBP_PalRandomIncidentPlacementEggDataComponent_C
---@field BP_PalRandomIncidentPlacementEggDataComponent1 UBP_PalRandomIncidentPlacementEggDataComponent_C
---@field BP_PalRandomIncidentPlacementDropItemDataComponent2 UBP_PalRandomIncidentPlacementDropItemDataComponent_C
---@field BP_PalRandomIncidentPlacementDropItemDataComponent1 UBP_PalRandomIncidentPlacementDropItemDataComponent_C
---@field BP_PalRandomIncidentPlacementDropItemDataComponent UBP_PalRandomIncidentPlacementDropItemDataComponent_C
---@field BP_PalRandomIncidentPlacementEggDataComponent UBP_PalRandomIncidentPlacementEggDataComponent_C
---@field StaticMesh UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
ABP_PalRandomIncidentObjectPlacement_PalNest_Yeti_C = {}

---@return ABP_PalRandomIncidentObjectPlacement_PalNest_Yeti_C
function ABP_PalRandomIncidentObjectPlacement_PalNest_Yeti_C:get() end



